###listar genero
GET http://127.0.0.1:3000/genero/


###agregar genero


POST HTTP://127.0.0.1:3000/genero/   
Content-Type: application/json

{
    "nombre": "Acción"
}
###update genero
PUT http://127.0.0.1:3000/genero/
Content-Type: application/json
    
    {
        "nombre": "asion",
        "id":"67e4766eac30c5e03d5a3980"
        }

###delete genero
DELETE http://127.0.0.1:3000/genero/
Content-Type: application/json

{
    "id":"67e4766eac30c5e03d5a3980"
    }




###listar pelicula
GET HTTP://127.0.0.1:3000/pelicula/  

### add de pelicula
POST HTTP://127.0.0.1:3000/pelicula/   
Content-Type: application/json

{
    "codigo": 100,
    "titulo":"SuperMdsfsdfsdfsd",
    "protagonista": "richar mooz",
    "duracion":120,
    "resumen": "yyyyyyyyyyyyyy",
    "foto": "13.jpg",
    "genero": "67e411d8585a485b54864c11"
}

###update de pelicula
PUT http://127.0.0.1:3000/pelicula/
Content-Type: application/json

{
    "id":"67e4837714ff7bcba859926c",
    "codigo":2,
    "titulo":" la maria",
    "protagonista":"homero",
    "duracion":200,
    "resumen":"azazazazaza",
    "foto":"img",   
    "genero":"67e4766eac30c5e03d5a3980"
}

###agregar usuario
POST http://127.0.0.1:3000/usuario/
Content-Type: application/json

{
    "usuario": "ferney",
    "password": "0000",
    "nombres": "ferney",
    "apellidos": "muñoz",
    "correo": "ferney.m2003@gmail.com"
}

